version: '3.1'

services:
  ani_service:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/

    environment:
      - MONGO_DB_URI=ani_db://ani_db:27017

    depends_on:
      - ani_db
    networks:
      - ani_network

  ani_db:
    image: mongo:3.4
    restart: unless-stopped
    container_name: ani_db
    volumes:
      - ani-data:/data/db
      - ./../AnimeList.csv:/data/db/AnimeList.csv
    networks:
      - ani_network

networks:
  ani_network:

volumes:
  ani-data:
