version: '3.1'

services:
  ani_list_service:
    build:
      context: ./../anime_list/
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./../anime_list/:/usr/src/app/
     
        


    environment:
      - MONGO_DB_URI=mongodb://ani_list:27017
      - FLASK_APP=/usr/src/app/run.py
      - CONFIG_CLASS_NAME=DevelopmentConfig
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DB_USER=autea_dev
      - DB_PWD=autea123
      - USER_SERVICE_URL=http://192.168.1.107:8081
      - USERLIST_SERVICE_URL=http://192.168.1.107:8082

    depends_on:
      - ani_list
    networks:
      - ani_user_lists_network
    links:
      - ani_users_service


  ani_users_service:
    build:
      context: ./../anime_users/
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    volumes:
      - ./../anime_users/:/usr/src/app/


    environment:
      - MONGO_DB_URI=mongodb://ani_users:27017
      - FLASK_APP=/usr/src/app/run.py
      - CONFIG_CLASS_NAME=DevelopmentConfig
      - FLASK_ENV=development
      - FLASK_DEBUG=1

    depends_on:
      - ani_users
    networks:
      - ani_user_lists_network

  ani_user_lists_service:
    build:
      context: ./../anime_ratings/
      dockerfile: Dockerfile
    ports:
      - "8082:5000"
    volumes:
      - ./../anime_ratings/:/usr/src/app/


    environment:
      - MONGO_DB_URI=mongodb://ani_user_lists:27017
      - FLASK_APP=/usr/src/app/run.py
      - CONFIG_CLASS_NAME=DevelopmentConfig
      - FLASK_ENV=development
      - FLASK_DEBUG=1

    depends_on:
      - ani_user_lists
    networks:
      - ani_user_lists_network

  ani_list:
    image: mongo:3.4
    restart: unless-stopped
    container_name: ani_list
    ports:
      - '27017:27017'
    volumes:
      - ani_data:/data/db
      - .:/data/db/data
    networks:
      - ani_user_lists_network


  ani_users:
    image: mongo:3.4
    restart: unless-stopped
    container_name: ani_users
    ports:
      - '27018:27017'
    volumes:
      - ani_users_data:/data/db
      - .:/data/db/data
    networks:
      - ani_user_lists_network


  ani_user_lists:
    image: mongo:3.4
    restart: unless-stopped
    container_name: ani_user_lists
    ports:
      - '27019:27017'
    volumes:
      - ani_user_lists_data:/data/db
      - .:/data/db/data
    networks:
      - ani_user_lists_network

networks:
  ani_list_network:
    driver: bridge
  ani_users_network:    
    driver: bridge
  ani_user_lists_network:
    driver: bridge
    

volumes:
  ani_data:
  ani_users_data:
  ani_user_lists_data:
